# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Weighted least-squares cross-products for beta-binomial IRLS
#'
#' Computes the symmetric information matrix \eqn{X^\top W X} and score
#' target \eqn{X^\top W z} in compiled code. This is an internal kernel used
#' by `bbreg()`.
#'
#' @param x Numeric design matrix.
#' @param weight Positive working-weight vector.
#' @param response Numeric working-response vector.
#' @return A list with `information` and `score_target`.
#' @keywords internal
bb_wls_system_cpp <- function(x, weight, response) {
    .Call(`_BARCS_bb_wls_system_cpp`, x, weight, response)
}

#' Compiled weighted least-squares solve for beta-binomial IRLS
#'
#' Forms \eqn{X^\top W X} and \eqn{X^\top W z}, solves the symmetric system,
#' and optionally returns its inverse in one compiled call.
#'
#' @param x Numeric design matrix.
#' @param weight Positive working-weight vector.
#' @param response Numeric working-response vector.
#' @param covariance Whether to return the inverse information matrix.
#' @return A list with `coefficient` and, when requested, `covariance`.
#' @keywords internal
bb_wls_solve_cpp <- function(x, weight, response, covariance = FALSE) {
    .Call(`_BARCS_bb_wls_solve_cpp`, x, weight, response, covariance)
}

#' Count guide barcodes in FASTQ files
#'
#' Compiled entry point behind [barcs_quant()]. It builds the guide index
#' once and scans each FASTQ file in turn, so the library FASTA is parsed a
#' single time no matter how many samples are supplied.
#'
#' @param library_path Path to the guide library FASTA file.
#' @param fastq_path Character vector of plain-text FASTQ paths. Compressed
#'   input must be expanded by the caller first.
#' @param verbose Write progress to the standard error stream.
#'
#' @return A list with the guide names and sequences, the guide-by-sample
#'   count matrix, per-sample read and mapped-read totals, a per-sample
#'   reverse-complement flag, the detected guide length, and the number of
#'   library entries dropped as repeated, off-length, or non-ACGT.
#'
#' @keywords internal
barcs_quant_cpp <- function(library_path, fastq_path, verbose = FALSE) {
    .Call(`_BARCS_barcs_quant_cpp`, library_path, fastq_path, verbose)
}

